sonar.projectKey=retail-store-sample-app
sonar.projectName=Retail Store Sample App
sonar.sourceEncoding=UTF-8

sonar.sources=src

sonar.exclusions=**/build/**,**/target/**,**/node_modules/**,**/dist/**,**/.gradle/**,**/vendor/**,**/chart/**

sonar.go.coverage.reportPaths=src/catalog/coverage.out
sonar.javascript.lcov.reportPaths=src/checkout/coverage/lcov.info
